"""Recognition of visible AI-image watermarks.

Visible marks are useful provenance hints, but they are not cryptographic proof:
watermarks can be cropped, copied, or added to an image.  The detector therefore
returns vendor matches and an evidence level instead of silently changing a
model prediction.
"""

from __future__ import annotations

import argparse
import io
import re
import shutil
import subprocess
from collections import deque
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from PIL import Image, ImageOps, UnidentifiedImageError

from .config import AppConfig, WatermarkConfig, config_argument_parser, load_config


# Aliases intentionally include both the visible Chinese labels and product
# names commonly emitted in English UI/export paths.  Keep aliases lowercase
# and normalized through ``normalize_text`` before matching.
VENDOR_SIGNATURES: dict[str, tuple[str, ...]] = {
    "doubao": ("豆包", "doubao", "seedream", "字节跳动", "bytedance"),
    "jimeng": ("即梦", "jimeng", "dreamina"),
    "tongyi": ("通义万相", "通义", "tongyi", "wanxiang"),
    "hunyuan": ("混元", "hunyuan", "腾讯混元"),
    "dall-e": ("dall-e", "dalle", "openai", "chatgpt"),
    "google-imagen": ("google imagen", "imagen", "gemini"),
    "midjourney": ("midjourney", "midjourney ai"),
    "adobe-firefly": ("adobe firefly", "firefly"),
    "stable-diffusion": ("stable diffusion", "stability ai", "sdxl"),
    "flux": ("black forest labs", "flux"),
    "ideogram": ("ideogram",),
    "leonardo": ("leonardo ai", "leonardo"),
    "microsoft-designer": ("microsoft designer", "bing image creator", "copilot"),
    "meta-ai": ("meta ai",),
    "canva": ("canva magic media", "canva ai"),
    "generic-ai": ("ai generated", "ai-generated", "generated by ai", "ai生成", "人工智能生成"),
}

_VENDOR_LABELS_ZH = {
    "doubao": "豆包（字节/Seedream）",
    "jimeng": "即梦（Dreamina）",
    "tongyi": "通义万相",
    "hunyuan": "腾讯混元",
    "dall-e": "OpenAI DALL·E/ChatGPT",
    "google-imagen": "Google Imagen/Gemini",
    "midjourney": "Midjourney",
    "adobe-firefly": "Adobe Firefly",
    "stable-diffusion": "Stable Diffusion/Stability AI",
    "flux": "FLUX",
    "ideogram": "Ideogram",
    "leonardo": "Leonardo AI",
    "microsoft-designer": "Microsoft Designer/Bing/Copilot",
    "meta-ai": "Meta AI",
    "canva": "Canva AI",
    "generic-ai": "AI 生成标识（未识别厂商）",
}


def normalize_text(value: str) -> str:
    """Normalize OCR and metadata text for resilient alias matching."""
    value = value.casefold().replace("·", "-").replace("•", "-")
    return re.sub(r"[\s\u3000]+", " ", value).strip()


def detect_watermark_text(text: str, *, source: str = "ocr") -> list[dict[str, str]]:
    """Return one match per vendor found in OCR/metadata text.

    Matching is substring based because OCR frequently inserts punctuation or
    drops part of a short watermark.  The original matched alias is retained
    for auditability.
    """
    normalized = normalize_text(text)
    compact = re.sub(r"\s+", "", normalized)
    matches: list[dict[str, str]] = []
    for vendor, aliases in VENDOR_SIGNATURES.items():
        alias = next(
            (
                candidate
                for candidate in aliases
                if normalize_text(candidate) in normalized
                or re.sub(r"\s+", "", normalize_text(candidate)) in compact
            ),
            None,
        )
        if alias is not None:
            matches.append(
                {
                    "vendor": vendor,
                    "vendor_label_zh": _VENDOR_LABELS_ZH[vendor],
                    "matched_text": alias,
                    "source": source,
                }
            )
    return matches


def _ocr_region(image: Image.Image, config: WatermarkConfig) -> tuple[str, str | None]:
    """OCR one image region, returning text and an optional error status."""
    tool = (config.tesseract_path or "").strip() or shutil.which("tesseract")
    if not tool:
        return "", "tesseract_not_installed"
    if config.tesseract_path and (Path(tool).is_absolute() or "/" in tool) and not Path(tool).is_file():
        return "", "tesseract_not_installed"
    prepared = ImageOps.grayscale(image)
    prepared = ImageOps.autocontrast(prepared)
    prepared = prepared.resize(
        (max(1, prepared.width * config.upscale_factor), max(1, prepared.height * config.upscale_factor)),
        Image.Resampling.LANCZOS,
    )
    # OCR accepts PNG bytes through stdin, so no user-controlled temporary path
    # is passed to a shell or left behind after a scan.
    buffer = io.BytesIO()
    prepared.save(buffer, format="PNG")
    command = [tool, "stdin", "stdout", "--psm", "11", "-l", config.languages]
    try:
        completed = subprocess.run(
            command,
            input=buffer.getvalue(),
            capture_output=True,
            timeout=config.ocr_timeout_seconds,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return "", "ocr_timeout"
    except (OSError, ValueError):
        return "", "ocr_execution_error"
    if completed.returncode != 0:
        # A machine often has English data but not chi_sim. Retry with English
        # so a visible "AI generated" or vendor name is still recognized.
        if config.languages != "eng":
            fallback = [tool, "stdin", "stdout", "--psm", "11", "-l", "eng"]
            try:
                completed = subprocess.run(
                    fallback,
                    input=buffer.getvalue(),
                    capture_output=True,
                    timeout=config.ocr_timeout_seconds,
                    check=False,
                )
            except (OSError, ValueError, subprocess.TimeoutExpired):
                return "", "ocr_language_unavailable"
        if completed.returncode != 0:
            return "", "ocr_failed"
    output = completed.stdout
    if isinstance(output, bytes):
        output = output.decode("utf-8", errors="replace")
    return str(output or ""), None


def _corner_regions(image: Image.Image, fraction: float) -> Iterable[tuple[str, Image.Image]]:
    width, height = image.size
    crop_width = max(1, round(width * fraction))
    crop_height = max(1, round(height * fraction))
    boxes = {
        "top_left": (0, 0, crop_width, crop_height),
        "top_right": (width - crop_width, 0, width, crop_height),
        "bottom_left": (0, height - crop_height, crop_width, height),
        "bottom_right": (width - crop_width, height - crop_height, width, height),
    }
    for name, box in boxes.items():
        yield name, image.crop(box)


def _looks_like_doubao_corner_mark(image: Image.Image, fraction: float) -> bool:
    """Detect the characteristic white ``豆包AI生成`` corner lockup.

    Doubao exports use a compact, bright multi-glyph mark.  This fallback is
    deliberately conservative and only runs when OCR is unavailable; it looks
    for a dense group of small connected components in the lower-right edge.
    OpenCV remains optional, so installations without the CV extra still work
    with OCR when configured.
    """
    try:
        import numpy as np
    except ImportError:
        return False
    try:
        import cv2
    except ImportError:
        cv2 = None
    width, height = image.size
    left = max(0, round(width * (1 - fraction)))
    top = max(0, round(height * (1 - fraction)))
    corner = image.crop((left, top, width, height))
    if corner.height < 32 or corner.width < 32:
        return False
    rgb_corner = np.asarray(image.crop((left, top, width, height)).convert("RGB"))
    rgb_roi = rgb_corner[round(rgb_corner.shape[0] * 0.45) :]
    # The exported lockup is near-white and low-saturation, even when the
    # underlying scene is strongly coloured.  A small opening removes isolated
    # highlights before connected-component analysis.
    luminance = rgb_roi.mean(axis=2)
    spread = rgb_roi.max(axis=2) - rgb_roi.min(axis=2)
    binary = (luminance > 130) & (spread < 35)
    if cv2 is not None:
        binary = cv2.morphologyEx(binary.astype("uint8"), cv2.MORPH_OPEN, np.ones((2, 2), np.uint8)).astype(bool)
    components: list[tuple[int, int, int, int, int]] = []
    if cv2 is not None:
        _count, _labels, stats, _centroids = cv2.connectedComponentsWithStats(binary.astype("uint8"))
        components = [tuple(int(value) for value in stat) for stat in stats[1:]]
    else:
        # Small pure-numpy fallback keeps the key Doubao detector usable when
        # the optional OpenCV extra is not installed.
        visited = np.zeros(binary.shape, dtype=bool)
        for y, x in zip(*np.where(binary & ~visited)):
            if visited[y, x]:
                continue
            queue = deque([(int(y), int(x))])
            visited[y, x] = True
            min_x = max_x = int(x)
            min_y = max_y = int(y)
            area = 0
            while queue:
                cy, cx = queue.pop()
                area += 1
                min_x, max_x = min(min_x, cx), max(max_x, cx)
                min_y, max_y = min(min_y, cy), max(max_y, cy)
                for ny, nx in ((cy - 1, cx), (cy + 1, cx), (cy, cx - 1), (cy, cx + 1)):
                    if 0 <= ny < binary.shape[0] and 0 <= nx < binary.shape[1] and binary[ny, nx] and not visited[ny, nx]:
                        visited[ny, nx] = True
                        queue.append((ny, nx))
            components.append((min_x, min_y, max_x - min_x + 1, max_y - min_y + 1, area))
    components = [
        stat
        for stat in components
        if stat[0] >= binary.shape[1] * 0.65
        and 6 <= stat[4] <= binary.shape[0] * binary.shape[1] * 0.08
        and 1 <= stat[2] <= binary.shape[1] * 0.45
        and 2 <= stat[3] <= binary.shape[0] * 0.55
    ]
    component_area = sum(int(stat[4]) for stat in components)
    density = component_area / float(binary.shape[0] * binary.shape[1])
    return len(components) >= 8 and density >= 0.015


def inspect_watermark(path: str | Path, config: AppConfig | WatermarkConfig) -> dict[str, Any]:
    """Inspect visible watermark text in the four corners of an image."""
    settings = config.watermark if isinstance(config, AppConfig) else config
    max_image_pixels = config.data.max_image_pixels if isinstance(config, AppConfig) else None
    if not settings.enabled:
        return {"available": True, "status": "disabled", "detected": False, "matches": [], "regions": []}
    source = Path(path)
    try:
        with Image.open(source) as opened:
            pixel_count = opened.width * opened.height
            if max_image_pixels is not None and pixel_count > max_image_pixels:
                return {
                    "available": False,
                    "status": "image_too_large",
                    "detected": False,
                    "matches": [],
                    "regions": [],
                    "pixel_count": pixel_count,
                    "max_image_pixels": max_image_pixels,
                }
            image = ImageOps.exif_transpose(opened).convert("RGB")
    except (OSError, UnidentifiedImageError):
        return {"available": False, "status": "unreadable", "detected": False, "matches": [], "regions": []}

    # Keep OCR bounded while preserving enough pixels for small corner marks.
    scale = min(1.0, settings.max_dimension / max(image.size))
    if scale < 1:
        image = image.resize((max(1, round(image.width * scale)), max(1, round(image.height * scale))), Image.Resampling.LANCZOS)

    region_reports: list[dict[str, Any]] = []
    all_matches: list[dict[str, str]] = []
    ocr_errors: list[str] = []
    if settings.ocr_enabled:
        for region_name, region in _corner_regions(image, settings.corner_fraction):
            text, error = _ocr_region(region, settings)
            matches = detect_watermark_text(text, source=f"ocr:{region_name}")
            all_matches.extend(matches)
            region_report: dict[str, Any] = {"region": region_name, "text": text[:512], "matches": matches}
            if error:
                region_report["status"] = error
                ocr_errors.append(error)
            else:
                region_report["status"] = "ok"
            region_reports.append(region_report)

    # The Chinese lockup is often too small or low-contrast for OCR.  This
    # shape fallback identifies the known Doubao placement without requiring a
    # language pack; it is only accepted in the bottom-right region.
    if _looks_like_doubao_corner_mark(image, settings.corner_fraction):
        all_matches.append(
            {
                "vendor": "doubao",
                "vendor_label_zh": _VENDOR_LABELS_ZH["doubao"],
                "matched_text": "豆包AI生成",
                "source": "pixel:bottom_right",
            }
        )

    # De-duplicate a vendor seen in multiple corners while preserving evidence.
    unique_matches: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for match in all_matches:
        key = (match["vendor"], match["matched_text"])
        if key not in seen:
            seen.add(key)
            unique_matches.append(match)
    status = "ok" if settings.ocr_enabled and not ocr_errors else (ocr_errors[0] if ocr_errors else "ocr_disabled")
    return {
        "available": True,
        "status": status,
        "detected": bool(unique_matches),
        "matches": unique_matches,
        "vendors": sorted({match["vendor"] for match in unique_matches}),
        "regions": region_reports,
        "confidence": "medium" if unique_matches else "none",
        "warning": "可见水印是线索，不是不可伪造的来源证明；水印可能被裁剪、复制或后加。",
    }


def argument_parser() -> argparse.ArgumentParser:
    parser = config_argument_parser("Detect visible AI-image watermarks in image corners.")
    parser.add_argument("--input", required=True, help="Image file or directory to inspect.")
    parser.add_argument("--output", required=True, help="Destination JSON report path.")
    return parser


def main(argv: list[str] | None = None) -> None:
    import json

    args = argument_parser().parse_args(argv)
    config = load_config(args.config, args.set)
    from .provenance import _write_json, iter_image_paths

    records = [{"path": str(path), "watermark": inspect_watermark(path, config)} for path in iter_image_paths(args.input, config.provenance.max_files)]
    _write_json({"schema_version": 1, "input": str(args.input), "records": records}, Path(args.output))


if __name__ == "__main__":
    main()
